### ISSUE TITLE
Quicknode部署问题

### ISSUE THREAD

**Issue by danjylon** [caict-4iot-dev/bif-doc#3]
部署Quicknode时，根据http://test.bifcore.bitfactory.cn/hello获得的chain_verson是1.9.2，但是拉取镜像时显示该镜像不存在，按照开放文档中的1.9.0-8版本拉取，镜像还是不存在。拉取1.2.1-4的镜像是可以的，但是在启动节点时提示证书过期
![1 9 2](https://user-images.githubusercontent.com/65285566/232438706-7e16e66a-3e7b-4791-9ebe-c5976948b568.png)
![1 9 0-8](https://user-images.githubusercontent.com/65285566/232438721-adbcb67c-272a-481f-9994-544b645ee001.png)
![证书错误](https://user-images.githubusercontent.com/65285566/232438732-6e3715b8-e0bd-4f05-9177-8e2ba9cb34c7.png)

**Comment by guojian1234** [comment]
v1.9.2的镜像会在本周内更新到docker hub，v1.2.1-4的镜像因为打包的时候比较早license.json文件已经过期了，因此验证不通过。
替换如下内容到config/license.json中可以启动v1.2.1-4
{
   "message" : {
      "authority" : "bif",
      "extra_data" : "123",
      "hardware" : "*",
      "id" : "36e9304d35453b445f523b22850c83e4",
      "network_id" : 0,
      "subject" : "bif",
      "time" : "2023-01-03T16:03:22+0800/2032-12-31T16:03:22+0800",
      "version" : "1.1.0"
   },
   "verification" : {
      "public_key" : "b0656604c1e9f5f657c240a718c05aa24b03f36a9426febcb619c95dde0abf76a748ed",
      "signature" : "06411ccdd3db991ff429ea9204700a38fa00fbc8d57896238060cbd302f68b2f8c05bab5e6709022bd867811b6cf62297ed8a49eaa271df10b390b285eef940a"
   }
}
欢迎加入技术交流群，沟通更方便，
![群链接](https://user-images.githubusercontent.com/36884984/232459339-6b4cd799-43c8-465d-b7ed-bb956e9b7f76.jpg)

**Comment by danjylon** [comment]
> v1.9.2的镜像会在本周内更新到docker hub，v1.2.1-4的镜像因为打包的时候比较早license.json文件已经过期了，因此验证不通过。 替换如下内容到config/license.json中可以启动v1.2.1-4 { "message" : { "authority" : "bif", "extra_data" : "123", "hardware" : "*", "id" : "36e9304d35453b445f523b22850c83e4", "network_id" : 0, "subject" : "bif", "time" : "2023-01-03T16:03:22+0800/2032-12-31T16:03:22+0800", "version" : "1.1.0" }, "verification" : { "public_key" : "b0656604c1e9f5f657c240a718c05aa24b03f36a9426febcb619c95dde0abf76a748ed", "signature" : "06411ccdd3db991ff429ea9204700a38fa00fbc8d57896238060cbd302f68b2f8c05bab5e6709022bd867811b6cf62297ed8a49eaa271df10b390b285eef940a" } } 欢迎加入技术交流群，沟通更方便， ![群链接](https://user-images.githubusercontent.com/36884984/232459339-6b4cd799-43c8-465d-b7ed-bb956e9b7f76.jpg)

非常感谢您的解答

**Comment by FutureBusinessCooperation** [comment]
您好，技术交流群可以拉我一下嘛？ 我的V：W927520_

**Comment by caict-develop-zhangbo** [comment]
> 您好，技术交流群可以拉我一下嘛？ 我的V：W927520_
![Catch(01-19-11-01-17)](https://github.com/caict-4iot-dev/bif-doc/assets/68949988/7dc817e2-0635-4189-9a88-b59f2a5ba549)
您扫码加一下群。
